

# This file was *autogenerated* from the file makeGraphs.sage
from sage.all_cmdline import *   # import sage library

_sage_const_11 = Integer(11); _sage_const_5 = Integer(5)
for g in digraphs.tournaments_nauty(_sage_const_11 , min_out_degree=_sage_const_5 ,max_out_degree=_sage_const_5 ):
    print(str(g.to_dictionary()))

