

# This file was *autogenerated* from the file makeGraphs.sage
from sage.all_cmdline import *   # import sage library

_sage_const_7 = Integer(7); _sage_const_3 = Integer(3)
for g in digraphs.tournaments_nauty(_sage_const_7 , min_out_degree=_sage_const_3 ,max_out_degree=_sage_const_3 ):
    print(str(g.to_dictionary()))

